@startuml GetCardRequirements

actor "Player" as Player
participant "GameHub" as Hub
participant "GameService" as GameSvc
participant "Card" as Card

Player -> Hub: Get requirements for card
activate Hub
Hub -> GameSvc: Get card requirements
activate GameSvc
GameSvc -> Card: Get requirements
activate Card
Card --> GameSvc: Requirements
deactivate Card

GameSvc -> Hub: Send requirements
Hub -> Player: Card requirements
deactivate GameSvc
deactivate Hub

@enduml
